# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'root@jler.vip:wangwenzhen/AutoBaseSpec.git'
target 'spec_localProject' do
 

pod 'BGNetwork', '~> 0.0.1'

pod 'BGAlertView', '~> 0.0.2’
end
